import { expect, test } from "@playwright/test";
test.use({ channel: "chrome", viewport: { width: 1600, height: 1000 } });
test("clock collection, inline editing, settings and fixed design", async ({ page }) => {
  const encode = (value: object) => Buffer.from(JSON.stringify(value)).toString("base64url");
  const token = encode({ alg:"none" }) + "." + encode({ role:"operator", exp:Math.floor(Date.now()/1000)+3600 }) + ".test";
  await page.context().addCookies([{ name:"dashboard_session", value:"test", url:"http://localhost:3000" }, { name:"dashboard_access_token", value:token, url:"http://localhost:3000" }]);
  await page.goto("http://localhost:3000/apps");
  await page.getByRole("button", { name:"Open Modern Clock details" }).click();
  await expect(page.getByRole("radiogroup", { name:"Clock templates" }).getByRole("radio")).toHaveCount(3);
  await page.screenshot({ path:"test-results/clock-collection.png", animations:"disabled" });
  await page.getByRole("radio", { name:"Executive Digital" }).click();
  await page.getByRole("button", { name:"Start with Selected Template" }).click();
  await expect(page.getByTestId("clock-canvas")).toHaveAttribute("data-layout","digital");
  await page.getByRole("button", { name:"Edit heading" }).click();
  await page.getByRole("textbox", { name:"Edit heading" }).fill("HEAD OFFICE");
  await page.getByRole("textbox", { name:"Edit heading" }).press("Enter");
  await expect(page.getByRole("button", { name:"Edit heading" })).toHaveText("HEAD OFFICE");
  await page.getByRole("button", { name:"◷ Clock", exact:true }).click();
  await page.getByRole("combobox", { name:"Time zone", exact:true }).selectOption("Asia/Tokyo");
  await page.getByRole("combobox", { name:"Time format" }).selectOption("12h");
  await expect(page.locator('input[type="color"]')).toHaveCount(0);
  await page.getByRole("combobox", { name:"Display type" }).selectOption("analog");
  await page.getByRole("button", { name:"Close clock settings" }).click();
  await expect(page.getByTestId("clock-canvas").getByRole("img")).toBeVisible();
  await page.screenshot({ path:"test-results/clock-editor.png" });
  await page.getByRole("button", { name:"Edit caption" }).click();
  await page.getByRole("textbox", { name:"Edit caption" }).fill("Welcome to our office");
  await page.getByRole("textbox", { name:"Edit caption" }).press("Enter");
  await expect(page.getByRole("button", { name:"Edit caption" })).toHaveText("Welcome to our office");
  await page.getByRole("button", { name:"9:16", exact:true }).click();
  await expect(page.getByTestId("clock-canvas")).toHaveClass(/portrait/);
  await page.screenshot({ path:"test-results/clock-portrait.png", animations:"disabled" });
  const canvas = await page.getByTestId("clock-canvas").boundingBox();
  expect(canvas!.height / canvas!.width).toBeCloseTo(16 / 9, 1);
  let saved: { name: string; config: Record<string, unknown> } | undefined;
  await page.route("**/api/apps/create-app", async route => {
    saved = route.request().postDataJSON();
    await route.fulfill({ status:201, json:{ success:true } });
  });
  await page.getByRole("button", { name:"Save and Close" }).click();
  await expect(page).toHaveURL("http://localhost:3000/apps");
  expect(saved?.config).toMatchObject({ heading:"HEAD OFFICE", caption:"Welcome to our office", timezone:"Asia/Tokyo", layout:"analog", format:"12h", theme:"paper" });
  await page.route("**/api/content/media", route => route.fulfill({ json:{ media:[{ id:"clock-e2e", filename:saved!.name, storage_path:"app://clock", app_config:saved!.config }] } }));
  await page.goto("http://localhost:3000/apps/configure?id=clock-e2e");
  await expect(page.getByRole("button", { name:"Edit heading" })).toHaveText("HEAD OFFICE");
  await expect(page.getByRole("button", { name:"Edit caption" })).toHaveText("Welcome to our office");
  await expect(page.getByTestId("clock-canvas")).toHaveAttribute("data-layout","analog");
  await page.setViewportSize({ width:900, height:1000 });
  const rail = await page.locator(".clock-editor-rail").boundingBox();
  const preview = await page.getByTestId("clock-canvas").boundingBox();
  expect(rail!.x + rail!.width).toBeLessThanOrEqual(preview!.x);
});
