import { test, expect } from "@playwright/test";
test.use({ channel: "msedge", viewport: { width: 1440, height: 1200 } });
test("snack menu is editable and persists its decorations and text", async ({ page }) => {
  test.setTimeout(90000);
  page.setDefaultTimeout(15000);
  await page.goto("http://localhost:3000/login");
  await page.getByLabel("E-POSTA ADRESİ").fill(process.env.E2E_EMAIL ?? "admin@remotescreen.dev");
  await page.getByLabel("ŞİFRE").fill(process.env.E2E_PASSWORD ?? "admin123");
  await page.getByRole("button", { name: "Giriş Yap" }).click();
  await page.waitForURL(/\/screens/);
  await page.goto("http://localhost:3000/apps/configure?type=restaurant-menu&template=snack");
  const canvas = page.getByTestId("restaurant-menu-canvas");
  await expect(canvas).toContainText("Snack Menu");
  await expect(canvas).toContainText("Nachos");
  await expect(canvas.locator("img")).toHaveCount(14);
  await canvas.screenshot({ path: "test-results/snack-editor.png" });
  await canvas.locator('[data-canvas-id="text:mini-pizza-name"]').dblclick();
  await page.getByLabel("Metni düzenle", { exact: true }).fill("Mini Margarita");
  await page.getByPlaceholder("Uygulama adı...").fill("Snack Menu kayıt testi");
  const saved = page.waitForResponse(r => r.url().endsWith("/api/apps/create-app") && r.request().method() === "POST");
  await page.getByRole("button", { name: /Kaydet/ }).click();
  const response = await saved;
  expect(response.status()).toBe(201);
  const { app } = await response.json();
  await page.goto(`http://localhost:3000/apps/configure?id=${app._id}&type=restaurant-menu`);
  await expect(canvas).toContainText("Mini Margarita");
  await expect(canvas.locator("img")).toHaveCount(14);
  await canvas.locator('[data-canvas-id="text:mini-pizza-price"]').dblclick();
  await page.getByLabel("Metni düzenle", { exact: true }).fill("$8");
  await page.getByPlaceholder("Uygulama adı...").click();
  const update = page.waitForResponse(r => r.url().includes(`/api/apps/update-app/${app._id}`));
  await page.getByRole("button", { name: /Kaydet/ }).click();
  expect((await update).status()).toBe(200);
  await page.goto(`http://localhost:4100/api/v1/apps/render/${app._id}`);
  await expect(page.locator("body")).toContainText("Mini Margarita");
  await expect(page.locator("body")).toContainText("$8");
  await page.setViewportSize({ width: 740, height: 1046 });
  await page.screenshot({ path: "test-results/snack-render.png" });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.screenshot({ path: "test-results/snack-landscape.png" });
  expect((await page.request.delete(`http://localhost:3000/api/content/media/${app._id}`)).status()).toBe(204);
});
